#!/bin/sh
#
# Starts thingyjp-dnsd
#

PID=/var/run/thingyjp-dnsd.pid

start() {
	printf "Starting thingyjp-dnsd: "
	start-stop-daemon -S -q -p $PID -b \
		--exec /usr/bin/dnsd
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping thingyjp-dnsd: "
	start-stop-daemon -K -q -p $PID
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
