#!/bin/sh
#
# Starts thingymcconfig.
#

CONFIGDIR=/space/thingymcconfig
CONFIGFILE=$CONFIGDIR/config.json

start() {
	printf "Starting thingymcconfig: "
	mkdir -p $CONFIGDIR
	start-stop-daemon -S -q -p /var/run/thingymcconfig.pid -b \
		--exec /usr/sbin/thingymcconfig -- -i mlan0 -c $CONFIGFILE -w
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping thingymcconfig: "
	start-stop-daemon -K -q -p /var/run/thingymcconfig.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
